import type { Metadata } from 'next'
import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'

import { Inter as FontSans } from 'next/font/google'
import { Suspense } from 'react'
import { cn } from '@/lib/utils'
import '@/styles/globals.css'

const fontSans = FontSans({
  subsets: ['vietnamese'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode
  params: { locale: string }
}>) {
  const messages = await getMessages()

  return (
    <html lang={locale} className='light'>
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased mb-20',
          fontSans.variable,
        )}
      >
        <NextIntlClientProvider messages={messages}>
          <Suspense>{children}</Suspense>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
